## Path settings
path:
  expname: s10-enc1-760K
  datadir: data/mcbench/
  logdir: logs/variant/
  train_file: train_data-s10-seq1.pt
  test_file: test_data-s10-seq1.pt
  load_ckpt: True


## Dataset settings
dataset:
  gateways_pos: [[-9.5405,   49.0814,   -0.0000],[-0.8726,  -49.9924,   -0.0000],[17.0593,   46.8702,    3.4878]]
  n_seq: 1

## Network settings
networks:
  init_weight: true
  transformer:
    dim: 325
    depth: 1
    heads: 4
    dim_head: 16
    mlp_dim: 128
    dropout: 0.1



## Training settings
training:
  lr: 1e-4
  weight_decay: 1e-4
  batch_size: 2048
  total_epoches: 9000
  i_save: 10    # model save epoch
  beta: 0.01   # loss weight
  T_max: 1000  # scheduler T_max