
## Path settings
path:
  expname: direct-s43-40
  datadir: data/fine-tune/
  logdir: logs/fine-tune/
  train_file: train_data-s43-40-60-seq1.pt
  test_file: test_data-s43-40-60-seq1.pt
  load_ckpt: True
  load_pretrain: True


## Dataset settings
dataset:
  n_seq: 1


## Network settings
networks:
  init_weight: true
  transformer:
    dim: 325
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dropout: 0.1



## Training settings
training:
  lr: 5e-4
  weight_decay: 1e-4
  batch_size: 1024
  total_epoches: 1000
  i_save: 10    # model save epoch
  loss: "L3"
  beta: 0.01   # loss weight
  T_max: 1000  # scheduler T_max
  loc_type: "2D"
