## Path settings
path:
  expname: s05
  datadir: data/mcbench/
  logdir: logs/mcbench/
  train_file: train_data-s05.t
  test_file: test_data-s05.t
  load_ckpt: True


## Dataset settings
dataset:
  gateways_pos: [[-17.9397,   17.3242,    1.7439],[-17.3665,  -17.9835,   -0.0000],[17.3242,   17.9397,    1.7439]]
  n_seq: 10

## Network settings
networks:
  init_weight: true
  transformer:
    dim: 325
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dropout: 0



## Training settings
training:
  lr: 1e-4
  weight_decay: 1e-4
  batch_size: 1024
  total_epoches: 6000
  i_save: 10    # model save epoch
  beta: 0.01   # loss weight
  T_max: 1000  # scheduler T_max
