## Path settings
path:
  expname: s16
  datadir: data/mcbench/
  logdir: logs/mcbench/
  train_file: train_data-s16-seq10.t
  test_file: test_data-s16-seq10.t
  load_ckpt: True


## Dataset settings
dataset:
  gateways_pos: [[-12.9190,   -1.1303,    0.9068],[12.5831,   -3.1373,    0.9068],[-3.8008,   12.4320,   -0.0000]]
  n_seq: 10

## Network settings
networks:
  init_weight: true
  transformer:
    dim: 325
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dropout: 0



## Training settings
training:
  lr: 1e-4
  weight_decay: 1e-4
  batch_size: 1024
  total_epoches: 13000
  i_save: 10    # model save epoch
  beta: 0.01   # loss weight
  T_max: 1000  # scheduler