## Path settings
path:
  expname: s37
  datadir: data/mcbench/
  logdir: logs/mcbench/
  train_file: train_data-s37-seq1.pt
  test_file: test_data-s37-seq1.pt
  load_ckpt: True


## Dataset settings
dataset:
  gateways_pos: [[-2.9301,   -8.5097,   -0.0000],[6.6883,    6.0222,   -0.0000],[-1.2096,   -4.8515,   -0.0000]]
  n_seq: 1

## Network settings
networks:
  init_weight: true
  transformer:
    dim: 325
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dropout: 0.1



## Training settings
training:
  lr: 1e-4
  weight_decay: 1e-4
  batch_size: 1024
  total_epoches: 9000
  i_save: 10    # model save epoch
  beta: 0.01   # loss weight
  T_max: 1000  # scheduler T_max