## Path settings
path:
  expname: s23
  datadir: data/mcbench/
  logdir: logs/mcbench/
  train_file: train_data-s23-seq1.t
  test_file: test_data-s23-seq1.t
  load_ckpt: True


## Dataset settings
dataset:
  gateways_pos: [[4.9931,    0.2617,   -0.0000],[-4.0451,    2.9389,   -0.0000],[-3.9932,   -3.0091,   -0.0000]]
  n_seq: 1

## Network settings
networks:
  init_weight: true
  transformer:
    dim: 325
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dropout: 0



## Training settings
training:
  lr: 1e-4
  weight_decay: 1e-4
  batch_size: 1024
  total_epoches: 13000
  i_save: 10    # model save epoch
  beta: 0.01   # loss weight
  T_max: 1000  # scheduler T_max