## Path settings
path:
  expname: s01
  datadir: data/mcbench/
  logdir: logs/mcbench/
  train_file: train_data-s01-seq10.t
  test_file: test_data-s01-seq10.t
  load_ckpt: True



## Dataset settings
dataset:
  gateways_pos: [[3.00,3.983,0.348],[-2.9318,4.0352,0.3488],[0.1741,-4.9848,0.3488]]
  n_seq: 10

## Network settings
networks:
  init_weight: true
  transformer:
    dim: 325
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dropout: 0



## Training settings
training:
  lr: 1e-4
  weight_decay: 1e-4
  batch_size: 1024
  total_epoches: 7000
  i_save: 10    # model save epoch
  beta: 0.01   # loss weight
  T_max: 1000  # scheduler T_max
