## Path settings
path:
  expname: s24
  datadir: data/mcbench/
  logdir: logs/mcbench/
  train_file: train_data-s24-seq10.t
  test_file: test_data-s24-seq10.t
  load_ckpt: True


## Dataset settings
dataset:
  gateways_pos: [[1.7101,   -4.6985,   -0.0000],[0.9517,    4.8962,    0.3488],[-1.2096,   -4.8515,   -0.0000]]
  n_seq: 10

## Network settings
networks:
  init_weight: true
  transformer:
    dim: 325
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dropout: 0



## Training settings
training:
  lr: 1e-4
  weight_decay: 1e-4
  batch_size: 1024
  total_epoches: 11000
  i_save: 10    # model save epoch
  beta: 0.01   # loss weight
  T_max: 1000  # scheduler T_max