## Path settings
path:
  expname: s04
  datadir: data/mcbench/
  logdir: logs/mcbench/
  train_file: train_data-s04.t
  test_file: test_data-s04.t
  load_ckpt: True


## Dataset settings
dataset:
  gateways_pos: [[19.2252,5.5127,-0.0000],[-7.8146,18.4101,-0.0000],[-8.4524,-18.1262,-0.0000]]
  n_seq: 10

## Network settings
networks:
  init_weight: true
  transformer:
    dim: 325
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dropout: 0



## Training settings
training:
  lr: 1e-4
  weight_decay: 1e-4
  batch_size: 1024
  total_epoches: 6000
  i_save: 10    # model save epoch
  beta: 0.01   # loss weight
  T_max: 1000  # scheduler T_max
