## Path settings
path:
  expname: s07
  datadir: data/mcbench/
  logdir: logs/mcbench/
  train_file: train_data-s07.t
  test_file: test_data-s07.t
  load_ckpt: True


## Dataset settings
dataset:
  gateways_pos: [[-33.4707,   10.2330,   -0.0000],[33.0125,   11.3671,    2.4415],[24.6884,   24.6884,    2.4415]]
  n_seq: 10

## Network settings
networks:
  init_weight: true
  transformer:
    dim: 324
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dropout: 0



## Training settings
training:
  lr: 1e-4
  weight_decay: 1e-4
  batch_size: 256
  total_epoches: 6000
  i_save: 1    # model save epoch
  beta: 0.01   # loss weight
