## Path settings
path:
  expname: s21
  datadir: data/mcbench/
  logdir: logs/mcbench/
  train_file: train_data-s21.t
  test_file: test_data-s21.t
  load_ckpt: True


## Dataset settings
dataset:
  gateways_pos: [[2.7892,    4.1351,    0.3488],[-3.9835,   -3.0017,    0.3488],[3.4648,   -3.5879,    0.3488]]
  n_seq: 10

## Network settings
networks:
  init_weight: true
  transformer:
    dim: 325
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dropout: 0



## Training settings
training:
  lr: 1e-4
  weight_decay: 1e-4
  batch_size: 1024
  total_epoches: 6000
  i_save: 10    # model save epoch
  beta: 0.01   # loss weight
  T_max: 1000  # scheduler T_max