## Path settings
path:
  expname: s10
  datadir: data/mcbench/
  logdir: logs/mcbench/
  train_file: train_data-s10.t
  test_file: test_data-s10.t
  load_ckpt: True


## Dataset settings
dataset:
  gateways_pos: [[-9.5405,   49.0814,   -0.0000],[-0.8726,  -49.9924,   -0.0000],[17.0593,   46.8702,    3.4878]]
  n_seq: 10

## Network settings
networks:
  init_weight: true
  transformer:
    dim: 324
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dropout: 0



## Training settings
training:
  lr: 1e-4
  weight_decay: 1e-4
  batch_size: 256
  total_epoches: 6000
  i_save: 1    # model save epoch
  beta: 0.01   # loss weight
