## Path settings
path:
  expname: s15
  datadir: data/mcbench/
  logdir: logs/mcbench/
  train_file: train_data-s15.t
  test_file: test_data-s15.t
  load_ckpt: True


## Dataset settings
dataset:
  gateways_pos: [[4.1481,   19.5153,    1.3951],[-18.2264,   -8.1149,    1.3951],[19.3586,    4.8267,    1.3951]]
  n_seq: 10

## Network settings
networks:
  init_weight: true
  transformer:
    dim: 324
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dropout: 0



## Training settings
training:
  lr: 1e-4
  weight_decay: 1e-4
  batch_size: 256
  total_epoches: 6000
  i_save: 1    # model save epoch
  beta: 0.01   # loss weight
