## Path settings
path:
  expname: s17
  datadir: data/mcbench/
  logdir: logs/mcbench/
  train_file: train_data-s17.t
  test_file: test_data-s17.t
  load_ckpt: True


## Dataset settings
dataset:
  gateways_pos: [[-12.9190,   -1.1303,    0.9068],[12.5831,   -3.1373,    0.9068],[-3.8008,   12.4320,   -0.0000]]
  n_seq: 10

## Network settings
networks:
  init_weight: true
  transformer:
    dim: 324
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dropout: 0



## Training settings
training:
  lr: 1e-4
  weight_decay: 1e-4
  batch_size: 256
  total_epoches: 6000
  i_save: 1    # model save epoch
  beta: 0.01   # loss weight
