## Path settings
path:
  expname: s02
  datadir: data/mcbench/
  logdir: logs/mcbench/
  train_file: train_data-s02.t
  test_file: test_data-s02.t
  load_ckpt: True



## Dataset settings
dataset:
  gateways_pos: [[2.41,9.68,0.70],[-2.25,9.74,0],[3.89,-9.18,0.69]]
  n_seq: 10

## Network settings
networks:
  init_weight: true
  transformer:
    dim: 324
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dropout: 0



## Training settings
training:
  lr: 1e-4
  weight_decay: 1e-4
  batch_size: 64
  total_epoches: 10000
  i_save: 1    # model save epoch
  beta: 0.01   # loss weight
